---
driver:
  name: docker
  hostname: watchdog.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: watchdog
  log_level: info
  state_top:
    base:
      "*":
        - watchdog
  pillars:
    top.sls:
      base:
        "*":
          - watchdog
  grains:
    noservices: True


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-2016.3'%>
      platform: ubuntu

verifier:
  name: inspec
  sudo: true


suites:
  - name: server
    provisioner:
      pillars-from-files:
        watchdog.sls: tests/pillar/server.sls

  - name: server_kernel_module
    provisioner:
      pillars-from-files:
        watchdog.sls: tests/pillar/server_kernel_module.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
